# Exception

Return reason for exception

```python
try:
    (do something)
except Exception as e:
    print(f"WARNING: {e}")
```
